// Fixed identifiers only: request data is never used as a SQL table name.
export const mapTables=[
  [
    "accounts",
    "users"
  ],
  [
    "profiles",
    "profiles"
  ],
  [
    "auth_sessions",
    "sessions"
  ],
  [
    "wallets",
    "wallets"
  ],
  [
    "game_saves",
    "gameStates"
  ],
  [
    "home_reservations",
    "homes"
  ],
  [
    "police_reservations",
    "policeBays"
  ],
  [
    "careers",
    "careers"
  ],
  [
    "career_notices",
    "careerNotices"
  ],
  [
    "housing_accounts",
    "housing.accounts"
  ],
  [
    "properties",
    "housing.homes"
  ],
  [
    "heist_accounts",
    "heists.accounts"
  ],
  [
    "club_accounts",
    "club.accounts"
  ],
  [
    "government_accounts",
    "government.accounts"
  ],
  [
    "election_votes",
    "government.votes"
  ],
  [
    "passenger_sessions",
    "passengers.sessions"
  ],
  [
    "site_visits",
    "siteStats.recent"
  ]
];
export const arrayTables=[
  [
    "passengers",
    "passengers.npcs"
  ],
  [
    "election_candidates",
    "government.candidates"
  ],
  [
    "wage_claims",
    "government.arrears"
  ],
  [
    "club_events",
    "club.events"
  ]
];
export const recordTables=[...mapTables,...arrayTables].map(([name])=>name).concat(['shared_state','wallet_components','processed_requests']);
