<script setup>
import CareerPanel from './CareerPanel.vue';
import RouteHud from '../danfo/components/RouteHud.vue';
import {getCourse} from './catalogue.js';
const props=defineProps({career:Object,bars:Object});
const c=props.career;
</script>
<template>
 <RouteHud v-if="c.nearbyWaste.value && !c.modal.value" class="route-hud--collection" :route="{id:'LAWMA',name:'Waste collection',stopIds:[]}" :current-stop-index="0" :hold-progress="c.collectionProgress.value" :inside-stop="true" :speed-allowed="!!c.closestWaste.value" :activity-label="c.busy.value&&c.collectionProgress.value>=1?'Collecting…':c.collection.failed?'Collection interrupted':'Stay stopped · collecting waste'" />
 <div class="career-actions" v-if="!c.modal.value">
  <button v-if="c.school.value" @click="c.modal.value='school'">🎓 School</button>
  <button v-if="c.workplace.value" @click="c.modal.value='work'">💼 {{c.workplace.value.name}}</button>
  <button v-if="c.closestWaste.value && c.collection.failed && !c.busy.value" @click="c.retryCollection()">Retry waste collection</button>
  <button v-if="c.target.value" :disabled="c.busy.value" @click="c.act({op:'inspect',targetId:c.target.value.id})">Check particulars · {{c.target.value.name}}</button>
  <span v-if="c.state.lesson">Class · {{Math.ceil((360-c.state.lesson.elapsed)/60)}}h remaining</span>
  <span v-if="c.state.shift">{{getCourse(c.state.job?.courseId)?.name}} · on shift</span>
  <span v-if="c.error.value" role="alert">{{c.error.value}}</span>
 </div>
 <div v-if="c.modal.value" class="career-shade" @click.self="c.modal.value=null"><div class="career-dialog" role="dialog" aria-modal="true" aria-label="School and careers"><CareerPanel :mode="c.modal.value" :state="c.state" :workplace="c.workplace.value" :bars="bars" :minute="c.minute.value" :occupied="c.occupied.value" :busy="c.busy.value" :error="c.error.value" @action="c.act" @close="c.modal.value=null"/></div></div>
 <div v-if="c.inspection.value && c.duty.value" class="career-inspection"><strong>{{c.inspection.value.name}}</strong><p>Crime: {{c.inspection.value.crime}} · Fines: ₦{{c.inspection.value.fines.toLocaleString()}}</p><button :disabled="c.busy.value" @click="c.act({op:'bribe',targetId:c.inspection.value.targetId})">Ask for bribe</button><button v-if="c.duty.value==='police'" :disabled="c.busy.value||c.inspection.value.crime<50" @click="c.act({op:'arrest',targetId:c.inspection.value.targetId})">Arrest</button><button :disabled="c.busy.value" @click="c.act({op:'release',targetId:c.inspection.value.targetId})">Release</button><button @click="c.inspection.value=null">Close</button></div>
 <div v-if="c.notice.value" class="career-shade"><div class="career-dialog career-stop" role="dialog" aria-modal="true" aria-label="Traffic stop"><h3>{{c.notice.value.service==='police'?'Police':'Traffic officer'}} · {{c.notice.value.officerName}}</h3><p>{{c.notice.value.kind==='arrest'?'You have been arrested. Report to the station.':'Your vehicle has been stopped for a particulars check.'}}</p><p v-if="c.notice.value.service==='lastma'">Outstanding fines: ₦{{c.notice.value.fines.toLocaleString()}}</p><p v-else>Crime rating: {{c.notice.value.crime}}</p><button v-if="c.notice.value.service==='lastma' && c.notice.value.fines>0" :disabled="c.busy.value" @click="c.act({op:'resolve-stop',choice:'fine'})">Pay outstanding fine</button><button v-if="c.notice.value.kind==='bribe'" :disabled="c.busy.value" @click="c.act({op:'resolve-stop',choice:'bribe'})">Pay bribe · ₦{{c.notice.value.amount.toLocaleString()}}</button><button v-if="c.notice.value.service==='police'" :disabled="c.busy.value" @click="c.act({op:'resolve-stop',choice:'station'})">Go to station · 24 hours</button><button v-if="c.notice.value.kind==='inspect' && c.notice.value.crime<50 && c.notice.value.fines<=0" :disabled="c.busy.value" @click="c.act({op:'resolve-stop',choice:'release'})">No offences · continue</button><p v-if="c.error.value" role="alert">{{c.error.value}}</p></div></div>
</template>
<style scoped>
.career-actions{position:absolute;right:12px;top:90px;z-index:65;display:flex;flex-direction:column;gap:5px;max-width:min(280px,38vw);pointer-events:auto}.career-actions span{background:#fff6d9;border-radius:9px;padding:6px;font-size:12px;color:#19253d}.career-actions button,.career-inspection button,.career-stop button{background:#ffdf4c;color:#19253d;border:0;border-radius:12px;padding:10px 12px;font:inherit;font-size:13px;white-space:normal;overflow-wrap:anywhere;cursor:pointer;min-height:40px}.career-shade{position:absolute;inset:0;background:#14203966;display:grid;place-items:center;z-index:1000;pointer-events:auto}.career-dialog{background:#fff7df;border-radius:20px;width:min(640px,94%);max-height:88%;overflow:auto;box-sizing:border-box}.career-stop{padding:20px}.career-stop button{margin:5px}.career-inspection{position:absolute;right:12px;top:100px;background:#fff7df;color:#19253d;border-radius:16px;padding:14px;z-index:1100;max-width:min(350px,70vw)}.career-inspection button{margin:3px}.career-inspection p{font-size:13px}button:disabled{opacity:.5}@media(pointer:coarse){.career-actions{top:75px}.career-dialog{max-height:90%}}
</style>
